In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=["cgpa","profile_score","lpa"])

In [7]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [9]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [10]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation="linear"))

C:\Users\harsh\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [17]:
optimixer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimixer)

In [18]:
x = df.drop(columns="lpa")
y = df['lpa']

In [20]:

model.fit(x,y,epochs=75,batch_size=1)

Epoch 1/75


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.7434 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 27.1705 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 19.1612  
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.6348
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.7739 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 22.6548  
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - loss: 23.0904
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - loss: 23.6313
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.1375 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.5176 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 11.8503 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 340us/step - loss: 16.5729
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.8592 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 19.4087  
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 16.5834  
Epoch 16/75
4/4 ━━━━━━━━━━━━━━

In [21]:
model.get_weights()

[array([[-0.37491795, -0.9531434 ],
        [ 1.1408491 , -0.41599533]], dtype=float32),
 array([0.07545099, 0.074736  ], dtype=float32),
 array([[-0.8782845],
        [-1.3232934]], dtype=float32),
 array([-0.07528437], dtype=float32)]

now for classification